spring:
  application:
    name: grocerystore
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: zeecoder
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
server:
  port: 8086
logging:
  level:
    root: info

